# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

#Theme settings
#
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

