# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

#Theme settings
#
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
#
locale                   : "en-US"
title                    : "Carlos M. Guio"
subtitle                 : "My personal web"
name                     : "Carlos M. Guío"
description              : "Data science and environmental stuff"
url                      :  https://cmguiob.github.io

# Site Author
author:
  name             : "Carlos M. Guio"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Environmental geologist, data scientist"
  location         : "Bogotá | Colombia"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "cm.guiob@email.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/cmguiob"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/carlos-guio-blanco/"

